return{
	Paldean_Wooper = true,
	Croagunk = true,
	Venipede = true,
	Foongus = true,
	Klink = true,
	Bunnelby = true,
	Skrelp = true,
	Mareanie = true,
	Dewpider = true,
	Salandit = true,
	Sandygast = true,
	Clobbopus = true,
	Rellor = true,
	Varoom = true,
}