return{
	Spinarak = true,
	Paldean_Wooper = true,
	Croagunk = true,
	Sewaddle = true,
	Venipede = true,
	Foongus = true,
	Klink = true,
	Bunnelby = true,
	Skrelp = true,
	Yungoos = true,
	Mareanie = true,
	Dewpider = true,
	Salandit = true,
	Sandygast = true,
	Jangmoo = true,
	Clobbopus = true,
	Rellor = true,
	Varoom = true,
}